<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Vector" data-toc-modified-id="Vector-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Vector</a></span><ul class="toc-item"><li><span><a href="#Dense-Vectors-밀집-벡터" data-toc-modified-id="Dense-Vectors-밀집-벡터-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Dense Vectors 밀집 벡터</a></span><ul class="toc-item"><li><span><a href="#numpy" data-toc-modified-id="numpy-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>numpy</a></span></li><li><span><a href="#mllib" data-toc-modified-id="mllib-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>mllib</a></span></li><li><span><a href="#ml" data-toc-modified-id="ml-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>ml</a></span></li><li><span><a href="#벡터-연산" data-toc-modified-id="벡터-연산-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>벡터 연산</a></span></li></ul></li><li><span><a href="#Sparse-Vector-희소-벡터" data-toc-modified-id="Sparse-Vector-희소-벡터-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Sparse Vector 희소 벡터</a></span></li></ul></li><li><span><a href="#Local-Matrix" data-toc-modified-id="Local-Matrix-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Local Matrix</a></span><ul class="toc-item"><li><span><a href="#Dense-Matrix-밀집-행렬" data-toc-modified-id="Dense-Matrix-밀집-행렬-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Dense Matrix 밀집 행렬</a></span></li><li><span><a href="#Sparse-Matrix-희소-행렬" data-toc-modified-id="Sparse-Matrix-희소-행렬-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Sparse Matrix 희소 행렬</a></span><ul class="toc-item"><li><span><a href="#scipy" data-toc-modified-id="scipy-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>scipy</a></span></li></ul></li><li><span><a href="#Sparse-Vectors의-SRC(Compressed-Aparse-Row)-or-Yale-Format" data-toc-modified-id="Sparse-Vectors의-SRC(Compressed-Aparse-Row)-or-Yale-Format-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Sparse Vectors의 SRC(Compressed Aparse Row) or Yale Format</a></span><ul class="toc-item"><li><span><a href="#희소-행렬로-변환" data-toc-modified-id="희소-행렬로-변환-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>희소 행렬로 변환</a></span></li></ul></li></ul></li><li><span><a href="#분산-Matrix" data-toc-modified-id="분산-Matrix-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>분산 Matrix</a></span><ul class="toc-item"><li><span><a href="#Row-Matrix" data-toc-modified-id="Row-Matrix-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Row Matrix</a></span></li><li><span><a href="#Indexed-Row-Matrix" data-toc-modified-id="Indexed-Row-Matrix-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Indexed Row Matrix</a></span></li></ul></li><li><span><a href="#Labeled-Point" data-toc-modified-id="Labeled-Point-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Labeled Point</a></span><ul class="toc-item"><li><span><a href="#label,-features-구성" data-toc-modified-id="label,-features-구성-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>label, features 구성</a></span></li><li><span><a href="#sparse-vector로-feature-구성" data-toc-modified-id="sparse-vector로-feature-구성-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>sparse vector로 feature 구성</a></span></li></ul></li><li><span><a href="#RDD-데이터를--LabeledPoint로-변환" data-toc-modified-id="RDD-데이터를--LabeledPoint로-변환-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>RDD 데이터를  LabeledPoint로 변환</a></span><ul class="toc-item"><li><span><a href="#Spark로-RDD-생성" data-toc-modified-id="Spark로-RDD-생성-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Spark로 RDD 생성</a></span></li><li><span><a href="#LabeledPoint-생성" data-toc-modified-id="LabeledPoint-생성-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>LabeledPoint 생성</a></span></li><li><span><a href="#정리" data-toc-modified-id="정리-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>정리</a></span></li></ul></li><li><span><a href="#svm의-입력파일-형식" data-toc-modified-id="svm의-입력파일-형식-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>svm의 입력파일 형식</a></span></li><li><span><a href="#MLUtils로-RDD읽기" data-toc-modified-id="MLUtils로-RDD읽기-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>MLUtils로 RDD읽기</a></span></li><li><span><a href="#TF(Term-Frequency)-단어-빈도로-텍스트로-변환" data-toc-modified-id="TF(Term-Frequency)-단어-빈도로-텍스트로-변환-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>TF(Term Frequency) 단어 빈도로 텍스트로 변환</a></span></li><li><span><a href="#TF-IDF" data-toc-modified-id="TF-IDF-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>TF-IDF</a></span></li><li><span><a href="#StandardScaler" data-toc-modified-id="StandardScaler-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>StandardScaler</a></span><ul class="toc-item"><li><span><a href="#데이터-생성" data-toc-modified-id="데이터-생성-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>데이터 생성</a></span></li><li><span><a href="#정규화-할-값만-추출" data-toc-modified-id="정규화-할-값만-추출-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>정규화 할 값만 추출</a></span></li><li><span><a href="#표준화" data-toc-modified-id="표준화-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>표준화</a></span></li></ul></li></ul></div>

# 데이터 변환
데이터를 정련, 가공, 일정한 형식을 가지도록 구성

- ETL (Extract, Transform, Load) : 추출, 변환, 다른 타겟으로 로딩
- 추출 : 데이터를 읽어 RDD, DataFrame을 생성
- 변환 : 분석 가능한 형식으로 변환
- 로딩 : 변환한 데이터 저장, DataFrame (label, features), RDD (Labeled Point)

## Vector

### Dense Vectors 밀집 벡터

#### numpy

In [1]:
import numpy as np
dv = np.array([1.0, 2.1, 3])

#### mllib

In [2]:
from pyspark.mllib.linalg import Vectors
dv1mllib=Vectors.dense([1.0, 2.1, 3])

In [3]:
print ("Dense vector: {}\nType: {}".format(dv1mllib, type(dv1mllib)))

Dense vector: [1.0,2.1,3.0]
Type: <class 'pyspark.mllib.linalg.DenseVector'>


#### ml

In [4]:
from pyspark.ml.linalg import Vectors

dv1ml=Vectors.dense([1.0, 2.1, 3])

In [5]:
print ("ml의 dense vector: {}".format(dv1ml))

ml의 dense vector: [1.0,2.1,3.0]


#### 벡터 연산
product, dot, norm

In [6]:
dv1mllib.dot(dv1mllib)

14.41

In [7]:
np.dot(dv,dv)

14.41

In [8]:
dv1mllib*dv1mllib

DenseVector([1.0, 4.41, 9.0])

### Sparse Vector 희소 벡터
0값이 아닌 NZ Nonzero만 저장

In [9]:
sv1 = Vectors.sparse(5,[0,1,4],[160.0,69.0,24.0])

In [10]:
type(sv1)

pyspark.ml.linalg.SparseVector

`toArray()` 함수로 sparse -> dense

In [11]:
sv1.toArray()

array([160.,  69.,   0.,   0.,  24.])

## Local Matrix

### Dense Matrix 밀집 행렬

In [12]:
from pyspark.mllib.linalg import Matrices

Matrices.dense(3, 2, [1,2,3,4,5,6])

DenseMatrix(3, 2, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0], False)

### Sparse Matrix 희소 행렬
0값이 아닌 NZ Nonzero만 저장
```
[1 0 2]
[0 0 3]
[4 5 6]
```
- 행 | 0 | 0 | 1 | 2 | 2 | 2
- 열 | 0 | 2 | 2 | 0 | 1 | 2
- 값 | 1 | 2 | 3 | 4 | 5 | 6

In [13]:
import numpy as np

row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

#### scipy

In [14]:
import scipy.sparse as sps

mtx = sps.csc_matrix((data, (row, col)), shape=(3, 3))

In [15]:
print (mtx.todense())

[[1 0 2]
 [0 0 3]
 [4 5 6]]


### Sparse Vectors의 SRC(Compressed Aparse Row) or Yale Format

In [16]:
from pyspark.mllib.linalg import Matrices

dm = Matrices.dense(6,4,[1, 2, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 0, 8])

In [17]:
dm.toArray()

array([[1., 0., 0., 0.],
       [2., 3., 0., 0.],
       [0., 0., 5., 0.],
       [0., 4., 6., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 8.]])

#### 희소 행렬로 변환
(행, 열, 열에서의 존재하는 숫자 누적 개수, 열 순서대로 존재하는 숫자 행의 위치, 들어가있는 NonZero값)

In [18]:
dm.toSparse()

SparseMatrix(6, 4, [0, 2, 4, 7, 8], [0, 1, 1, 3, 2, 3, 4, 5], [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], False)

In [19]:
sm = Matrices.sparse(3, 2, [0, 1, 3], [0, 2, 1], [9, 6, 8])

In [20]:
d=sm.toDense()

In [21]:
print (d)

DenseMatrix([[9., 0.],
             [0., 8.],
             [0., 6.]])


## 분산 Matrix
여러 기계(파티션)으로 존재

In [24]:
# SparkSession 생성
import pyspark
import os

myConf=pyspark.SparkConf()
spark = pyspark.sql.SparkSession\
    .builder\
    .master("local")\
    .appName("myApp")\
    .config(conf=myConf)\
    .getOrCreate()

### Row Matrix
List -> RDD -> Row Matrix

<strong>list<strong/>

In [22]:
p = [[1.0,2.0,3.0],[1.1,2.1,3.1],[1.2,2.2,3.3]]

<strong>RDD<strong/>

In [25]:
my = spark.sparkContext.parallelize(p)

In [26]:
my.collect()

[[1.0, 2.0, 3.0], [1.1, 2.1, 3.1], [1.2, 2.2, 3.3]]

<strong>Row Matrix<strong/>

In [27]:
from pyspark.mllib.linalg.distributed import RowMatrix

rm=RowMatrix(my)

In [28]:
print (type(rm))

<class 'pyspark.mllib.linalg.distributed.RowMatrix'>


In [29]:
rm.rows.collect()

[DenseVector([1.0, 2.0, 3.0]),
 DenseVector([1.1, 2.1, 3.1]),
 DenseVector([1.2, 2.2, 3.3])]

In [31]:
rm.numRows()

3

In [32]:
rm.numCols()

3

### Indexed Row Matrix
순서대로 저장됨

In [41]:
from pyspark.mllib.linalg.distributed import IndexedRow

irRdd = spark.sparkContext.parallelize([
    IndexedRow(1, [3, 1, 2]),
    IndexedRow(2, [1, 3, 2]),
    IndexedRow(3, [5, 4, 3]),
    IndexedRow(4, [6, 7, 4]),
    IndexedRow(5, [8, 9, 2]),
])

In [42]:
from pyspark.mllib.linalg.distributed import IndexedRowMatrix

irm = IndexedRowMatrix(irRdd)

In [43]:
irm.rows.collect()

[IndexedRow(1, [3.0,1.0,2.0]),
 IndexedRow(2, [1.0,3.0,2.0]),
 IndexedRow(3, [5.0,4.0,3.0]),
 IndexedRow(4, [6.0,7.0,4.0]),
 IndexedRow(5, [8.0,9.0,2.0])]

In [35]:
print(irm.numRows())
print(irm.numCols())

6
3


## Labeled Point
Local Vector, 레이블(label)이 있음(string type)

### label, features 구성
(label, features)

In [44]:
from pyspark.mllib.regression import LabeledPoint

LabeledPoint(1.0, [1.0, 2.0, 3.0])

LabeledPoint(1.0, [1.0,2.0,3.0])

### sparse vector로 feature 구성
sparse(10개, 위치, 값)

In [45]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors

LabeledPoint(1992, Vectors.sparse(10, {0: 3.0, 1:5.5, 2: 10.0}))

LabeledPoint(1992.0, (10,[0,1,2],[3.0,5.5,10.0]))

<strong>ml<strong/>
    
`Vectors.fromML()`을 사용 

In [ ]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors

LabeledPoint(1.0, Vectors.fromML(dv1ml))

## RDD 데이터를  LabeledPoint로 변환

In [46]:
_fsvm=os.path.join('data','sample_svm_data.txt')

In [47]:
import os

try:
    _f=open(_fsvm,'r')
    _lines=_f.readlines()
    _f.close()
except:
    print("An exception occurred")

In [48]:
_lines[0]

'1 0 2.52078447201548 0 0 0 2.004684436494304 2.000347299268466 0 2.228387042742021 2.228387042742023 0 0 0 0 0 0\n'

### Spark로 RDD 생성
어떻게 구분되어있는지 확인하기

In [49]:
_rdd=spark.sparkContext.textFile(_fsvm)\
    .map(lambda line: [float(x) for x in line.split()])

In [54]:
_rdd.collect()

[[1.0,
  0.0,
  2.52078447201548,
  0.0,
  0.0,
  0.0,
  2.004684436494304,
  2.000347299268466,
  0.0,
  2.228387042742021,
  2.228387042742023,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  2.857738033247042,
  0.0,
  0.0,
  2.619965104088255,
  0.0,
  2.004684436494304,
  2.000347299268466,
  0.0,
  2.228387042742021,
  2.228387042742023,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  2.857738033247042,
  0.0,
  2.061393766919624,
  0.0,
  0.0,
  2.004684436494304,
  0.0,
  0.0,
  2.228387042742021,
  2.228387042742023,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [1.0,
  0.0,
  0.0,
  2.061393766919624,
  2.619965104088255,
  0.0,
  2.004684436494304,
  2.000347299268466,
  0.0,
  0.0,
  0.0,
  0.0,
  2.055002875864414,
  0.0,
  0.0,
  0.0,
  0.0],
 [1.0,
  2.857738033247042,
  0.0,
  2.061393766919624,
  2.619965104088255,
  0.0,
  2.004684436494304,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  2.055002875864414,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  2.857738033247042,
  0.0,
  

(2) : 2차원 리스트, [0] : 첫번째 데이터

In [52]:
_rdd.take(2)[0]

[1.0,
 0.0,
 2.52078447201548,
 0.0,
 0.0,
 0.0,
 2.004684436494304,
 2.000347299268466,
 0.0,
 2.228387042742021,
 2.228387042742023,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

### LabeledPoint 생성
- 0번째 : Label
- 나머지 : feature

In [55]:
from pyspark.mllib.regression import LabeledPoint

_trainRdd0=_rdd.map(lambda line:LabeledPoint(line[0], line[1:]))

In [56]:
_trainRdd0.take(1)

[LabeledPoint(1.0, [0.0,2.52078447201548,0.0,0.0,0.0,2.004684436494304,2.000347299268466,0.0,2.228387042742021,2.228387042742023,0.0,0.0,0.0,0.0,0.0,0.0])]

<strong>구분 + LabelPoint 생성<strong/>

In [57]:
_trainRdd=spark.sparkContext.textFile(_fsvm)\
    .map(lambda line: [float(x) for x in line.split()])\
    .map(lambda p:LabeledPoint(p[0], p[1:]))

In [58]:
_trainRdd.take(1)

[LabeledPoint(1.0, [0.0,2.52078447201548,0.0,0.0,0.0,2.004684436494304,2.000347299268466,0.0,2.228387042742021,2.228387042742023,0.0,0.0,0.0,0.0,0.0,0.0])]

### 정리
데이터 변환 함수 + LabelPoint

In [60]:
def createLP(line):
    p = [float(x) for x in line.split()]
    return LabeledPoint(p[0], p[1:])

_rdd=spark.sparkContext.textFile(_fsvm)
trainRdd = _rdd.map(createLP)

trainRdd.take(1)

[LabeledPoint(1.0, [0.0,2.52078447201548,0.0,0.0,0.0,2.004684436494304,2.000347299268466,0.0,2.228387042742021,2.228387042742023,0.0,0.0,0.0,0.0,0.0,0.0])]

## svm의 입력파일 형식
DataFrame(RDD아님)

In [61]:
fsvm=os.path.join('data','sample_libsvm_data.txt')

In [62]:
dfsvm = spark.read.format("libsvm").load(fsvm)

In [63]:
dfsvm.printSchema()

root
 |-- label: double (nullable = true)
 |-- features: vector (nullable = true)



In [64]:
dfsvm.take(1)

[Row(label=0.0, features=SparseVector(692, {127: 51.0, 128: 159.0, 129: 253.0, 130: 159.0, 131: 50.0, 154: 48.0, 155: 238.0, 156: 252.0, 157: 252.0, 158: 252.0, 159: 237.0, 181: 54.0, 182: 227.0, 183: 253.0, 184: 252.0, 185: 239.0, 186: 233.0, 187: 252.0, 188: 57.0, 189: 6.0, 207: 10.0, 208: 60.0, 209: 224.0, 210: 252.0, 211: 253.0, 212: 252.0, 213: 202.0, 214: 84.0, 215: 252.0, 216: 253.0, 217: 122.0, 235: 163.0, 236: 252.0, 237: 252.0, 238: 252.0, 239: 253.0, 240: 252.0, 241: 252.0, 242: 96.0, 243: 189.0, 244: 253.0, 245: 167.0, 262: 51.0, 263: 238.0, 264: 253.0, 265: 253.0, 266: 190.0, 267: 114.0, 268: 253.0, 269: 228.0, 270: 47.0, 271: 79.0, 272: 255.0, 273: 168.0, 289: 48.0, 290: 238.0, 291: 252.0, 292: 252.0, 293: 179.0, 294: 12.0, 295: 75.0, 296: 121.0, 297: 21.0, 300: 253.0, 301: 243.0, 302: 50.0, 316: 38.0, 317: 165.0, 318: 253.0, 319: 233.0, 320: 208.0, 321: 84.0, 328: 253.0, 329: 252.0, 330: 165.0, 343: 7.0, 344: 178.0, 345: 252.0, 346: 240.0, 347: 71.0, 348: 19.0, 349: 28.0

## MLUtils로 RDD읽기

In [65]:
from pyspark.mllib.util import MLUtils

data = MLUtils.loadLibSVMFile(spark.sparkContext, fsvm)

In [66]:
label = data.map(lambda x: x.label)
features = data.map(lambda x: x.features)

In [67]:
label.take(5)

[0.0, 1.0, 1.0, 1.0, 1.0]

In [68]:
features.take(1)

[SparseVector(692, {127: 51.0, 128: 159.0, 129: 253.0, 130: 159.0, 131: 50.0, 154: 48.0, 155: 238.0, 156: 252.0, 157: 252.0, 158: 252.0, 159: 237.0, 181: 54.0, 182: 227.0, 183: 253.0, 184: 252.0, 185: 239.0, 186: 233.0, 187: 252.0, 188: 57.0, 189: 6.0, 207: 10.0, 208: 60.0, 209: 224.0, 210: 252.0, 211: 253.0, 212: 252.0, 213: 202.0, 214: 84.0, 215: 252.0, 216: 253.0, 217: 122.0, 235: 163.0, 236: 252.0, 237: 252.0, 238: 252.0, 239: 253.0, 240: 252.0, 241: 252.0, 242: 96.0, 243: 189.0, 244: 253.0, 245: 167.0, 262: 51.0, 263: 238.0, 264: 253.0, 265: 253.0, 266: 190.0, 267: 114.0, 268: 253.0, 269: 228.0, 270: 47.0, 271: 79.0, 272: 255.0, 273: 168.0, 289: 48.0, 290: 238.0, 291: 252.0, 292: 252.0, 293: 179.0, 294: 12.0, 295: 75.0, 296: 121.0, 297: 21.0, 300: 253.0, 301: 243.0, 302: 50.0, 316: 38.0, 317: 165.0, 318: 253.0, 319: 233.0, 320: 208.0, 321: 84.0, 328: 253.0, 329: 252.0, 330: 165.0, 343: 7.0, 344: 178.0, 345: 252.0, 346: 240.0, 347: 71.0, 348: 19.0, 349: 28.0, 356: 253.0, 357: 252.0

## TF(Term Frequency) 단어 빈도로 텍스트로 변환
텍스트 변환, 단어 빈도 계산

Hashing으로 자동으로 단어 빈도 계산

In [69]:
wikiRdd3 = spark.sparkContext\
    .textFile(os.path.join("data","ds_spark_wiki.txt"))\
    .map(lambda line: line.split())

(로우에서 벡터의 개수, {자동 id : 빈도})

In [70]:
from pyspark.mllib.feature import HashingTF

hashingTF = HashingTF()
tf = hashingTF.transform(wikiRdd3)
tf.collect()

[SparseVector(1048576, {1026674: 1.0}),
 SparseVector(1048576, {148618: 1.0, 183975: 1.0, 216207: 1.0, 261052: 1.0, 617454: 1.0, 696349: 1.0, 721336: 1.0, 816618: 1.0, 897662: 1.0}),
 SparseVector(1048576, {60386: 1.0, 177421: 1.0, 568609: 1.0, 569458: 1.0, 847171: 1.0, 850510: 1.0, 1040679: 1.0}),
 SparseVector(1048576, {261052: 4.0, 816618: 4.0}),
 SparseVector(1048576, {60386: 4.0, 594754: 4.0}),
 SparseVector(1048576, {21980: 1.0, 70882: 1.0, 274690: 1.0, 357784: 1.0, 549790: 1.0, 597434: 1.0, 804583: 1.0, 829803: 1.0, 935701: 1.0}),
 SparseVector(1048576, {154253: 1.0, 261052: 1.0, 438276: 1.0, 460085: 1.0, 585459: 1.0, 664288: 1.0, 816618: 1.0, 935701: 2.0, 948143: 1.0, 1017889: 1.0}),
 SparseVector(1048576, {270017: 1.0, 472985: 1.0, 511771: 1.0, 718483: 1.0, 820917: 1.0}),
 SparseVector(1048576, {34116: 1.0, 87407: 1.0, 276491: 1.0, 348943: 1.0, 482882: 1.0, 549350: 1.0, 721336: 1.0, 816618: 1.0, 1025622: 1.0}),
 SparseVector(1048576, {1769: 1.0, 151357: 1.0, 500659: 1.0, 54776

## TF-IDF
IDF : 몇 개의 문서에 씌였는지 반대로 계산

훈련데이터를 만들때 사용

In [71]:
from pyspark.mllib.feature import HashingTF, IDF

idf = IDF().fit(tf)
tfidf = idf.transform(tf)

In [72]:
tfidf.collect()

[SparseVector(1048576, {1026674: 1.7047}),
 SparseVector(1048576, {148618: 1.7047, 183975: 1.7047, 216207: 1.7047, 261052: 1.0116, 617454: 1.7047, 696349: 1.7047, 721336: 1.2993, 816618: 0.7885, 897662: 1.7047}),
 SparseVector(1048576, {60386: 1.2993, 177421: 1.7047, 568609: 1.7047, 569458: 1.7047, 847171: 1.7047, 850510: 1.7047, 1040679: 1.7047}),
 SparseVector(1048576, {261052: 4.0464, 816618: 3.1538}),
 SparseVector(1048576, {60386: 5.1971, 594754: 6.819}),
 SparseVector(1048576, {21980: 1.7047, 70882: 1.7047, 274690: 1.7047, 357784: 1.7047, 549790: 1.7047, 597434: 1.7047, 804583: 1.7047, 829803: 1.7047, 935701: 1.2993}),
 SparseVector(1048576, {154253: 1.7047, 261052: 1.0116, 438276: 1.7047, 460085: 1.7047, 585459: 1.7047, 664288: 1.7047, 816618: 0.7885, 935701: 2.5986, 948143: 1.7047, 1017889: 1.7047}),
 SparseVector(1048576, {270017: 1.7047, 472985: 1.7047, 511771: 1.7047, 718483: 1.7047, 820917: 1.7047}),
 SparseVector(1048576, {34116: 1.7047, 87407: 1.7047, 276491: 1.7047, 3489

## StandardScaler
키와 몸무게 같이 평균과 표준화를 맞추는 것 = zscore

### 데이터 생성

In [73]:
tRdd = spark.sparkContext\
    .textFile(os.path.join('data', 'ds_spark_heightweight.txt'))

### 정규화 할 값만 추출

In [74]:
tRdd.map(lambda x: x.split('\t')).take(1)

[['1', '65.78', '112.99']]

형 변환

In [75]:
tRdd.map(lambda x: x.split('\t')).map(lambda x: [str(x[0]), float(x[1]), float(x[2])]).take(1)

[['1', 65.78, 112.99]]

In [76]:
tRdd.map(lambda x: x.split('\t'))\
    .map(lambda x: [str(x[0]), float(x[1]), float(x[2])])\
    .take(1)

[['1', 65.78, 112.99]]

2개 값만 추출하여 저장

In [78]:
from pyspark.mllib.linalg import Vectors

_tRdd =tRdd\
    .map(lambda x: x.split('\t'))\
    .map(lambda x: [str(x[0]), float(x[1]), float(x[2])])\
    .map(lambda x: Vectors.dense([x[1], x[2]]))

list로 저장(위랑 같음)

In [79]:
from pyspark.mllib.linalg import Vectors

_tRdd =tRdd\
    .map(lambda x: x.split('\t'))\
    .map(lambda x: [str(x[0]), float(x[1]), float(x[2])])\
    .map(lambda x: [x[1], x[2]])

### 표준화

In [80]:
from pyspark.mllib.feature import StandardScaler
scaler1 = StandardScaler().fit(_tRdd)
scaler2 = StandardScaler(withMean=True, withStd=True).fit(_tRdd)

In [84]:
scaler1.transform(_tRdd).take(5)

[DenseVector([36.064, 8.7665]),
 DenseVector([39.2109, 10.5897]),
 DenseVector([38.0487, 11.873]),
 DenseVector([37.4017, 11.0436]),
 DenseVector([37.166, 11.1957])]

zscore값을 간편하게 구할 수 있음

In [81]:
scaler2.transform(_tRdd).take(5)

[DenseVector([-1.2458, -1.2299]),
 DenseVector([1.9011, 0.5934]),
 DenseVector([0.7388, 1.8767]),
 DenseVector([0.0919, 1.0473]),
 DenseVector([-0.1439, 1.1993])]